export const SET_ROLE = 'SET_ROLE'
export const GET_ROLE = 'GET_ROLE'


export const MAKE_REQUEST = 'MAKE_REQUEST'
export const FAIL_REQUEST = 'FAIL_REQUEST'


export const GET_STUDENT_LIST = 'GET_STUDENT_LIST'
export const REFRESH_STUDENT = 'REFRESH_STUDENT'
export const GET_STUDENT = 'GET_STUDENT'
export const ADD_STUDENT = 'ADD_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'


export const GET_FAMILY_LIST = 'GET_FAMILY_LIST'
export const GET_FAMILY = 'GET_FAMILY'
export const ADD_FAMILY = 'ADD_FAMILY'
export const UPDATE_FAMILY = 'UPDATE_FAMILY'
export const DELETE_FAMILY = 'DELETE_FAMILY'