// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_app.Model;

#nullable disable

namespace test_app.Model.migrations
{
    [DbContext(typeof(dbModel))]
    [Migration("20231009100229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("test_app.Model.FamilyMember", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.Property<int>("RelationshipId")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("test_app.Model.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NationalityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalityId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            NationalityId = 2,
                            CountryName = "Åland Islands"
                        },
                        new
                        {
                            NationalityId = 3,
                            CountryName = "Albania"
                        },
                        new
                        {
                            NationalityId = 4,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            NationalityId = 5,
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            NationalityId = 6,
                            CountryName = "AndorrA"
                        },
                        new
                        {
                            NationalityId = 7,
                            CountryName = "Angola"
                        },
                        new
                        {
                            NationalityId = 8,
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            NationalityId = 9,
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            NationalityId = 10,
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            NationalityId = 11,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            NationalityId = 12,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            NationalityId = 13,
                            CountryName = "Aruba"
                        },
                        new
                        {
                            NationalityId = 14,
                            CountryName = "Australia"
                        },
                        new
                        {
                            NationalityId = 15,
                            CountryName = "Austria"
                        },
                        new
                        {
                            NationalityId = 16,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            NationalityId = 17,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            NationalityId = 18,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            NationalityId = 19,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            NationalityId = 20,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            NationalityId = 21,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            NationalityId = 22,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            NationalityId = 23,
                            CountryName = "Belize"
                        },
                        new
                        {
                            NationalityId = 24,
                            CountryName = "Benin"
                        },
                        new
                        {
                            NationalityId = 25,
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            NationalityId = 26,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            NationalityId = 27,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            NationalityId = 28,
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            NationalityId = 29,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            NationalityId = 30,
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            NationalityId = 31,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            NationalityId = 32,
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            NationalityId = 33,
                            CountryName = "Brunei Darussalam"
                        },
                        new
                        {
                            NationalityId = 34,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            NationalityId = 35,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            NationalityId = 36,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            NationalityId = 37,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            NationalityId = 38,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            NationalityId = 39,
                            CountryName = "Canada"
                        },
                        new
                        {
                            NationalityId = 40,
                            CountryName = "Cape Verde"
                        },
                        new
                        {
                            NationalityId = 41,
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            NationalityId = 42,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            NationalityId = 43,
                            CountryName = "Chad"
                        },
                        new
                        {
                            NationalityId = 44,
                            CountryName = "Chile"
                        },
                        new
                        {
                            NationalityId = 45,
                            CountryName = "China"
                        },
                        new
                        {
                            NationalityId = 46,
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            NationalityId = 47,
                            CountryName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            NationalityId = 48,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            NationalityId = 49,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            NationalityId = 50,
                            CountryName = "Congo"
                        },
                        new
                        {
                            NationalityId = 51,
                            CountryName = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            NationalityId = 52,
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            NationalityId = 53,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            NationalityId = 54,
                            CountryName = "Cote D`Ivoire"
                        },
                        new
                        {
                            NationalityId = 55,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            NationalityId = 56,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            NationalityId = 57,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            NationalityId = 58,
                            CountryName = "Czech Republic"
                        },
                        new
                        {
                            NationalityId = 59,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            NationalityId = 60,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            NationalityId = 61,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            NationalityId = 62,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            NationalityId = 63,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            NationalityId = 64,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            NationalityId = 65,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            NationalityId = 66,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            NationalityId = 67,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            NationalityId = 68,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            NationalityId = 69,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            NationalityId = 70,
                            CountryName = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            NationalityId = 71,
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            NationalityId = 72,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            NationalityId = 73,
                            CountryName = "Finland"
                        },
                        new
                        {
                            NationalityId = 74,
                            CountryName = "France"
                        },
                        new
                        {
                            NationalityId = 75,
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            NationalityId = 76,
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            NationalityId = 77,
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            NationalityId = 78,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            NationalityId = 79,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            NationalityId = 80,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            NationalityId = 81,
                            CountryName = "Germany"
                        },
                        new
                        {
                            NationalityId = 82,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            NationalityId = 83,
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            NationalityId = 84,
                            CountryName = "Greece"
                        },
                        new
                        {
                            NationalityId = 85,
                            CountryName = "Greenland"
                        },
                        new
                        {
                            NationalityId = 86,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            NationalityId = 87,
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            NationalityId = 88,
                            CountryName = "Guam"
                        },
                        new
                        {
                            NationalityId = 89,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            NationalityId = 90,
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            NationalityId = 91,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            NationalityId = 92,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            NationalityId = 93,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            NationalityId = 94,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            NationalityId = 95,
                            CountryName = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            NationalityId = 96,
                            CountryName = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            NationalityId = 97,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            NationalityId = 98,
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            NationalityId = 99,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            NationalityId = 100,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            NationalityId = 101,
                            CountryName = "India"
                        },
                        new
                        {
                            NationalityId = 102,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            NationalityId = 103,
                            CountryName = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            NationalityId = 104,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            NationalityId = 105,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            NationalityId = 106,
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            NationalityId = 107,
                            CountryName = "Israel"
                        },
                        new
                        {
                            NationalityId = 108,
                            CountryName = "Italy"
                        },
                        new
                        {
                            NationalityId = 109,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            NationalityId = 110,
                            CountryName = "Japan"
                        },
                        new
                        {
                            NationalityId = 111,
                            CountryName = "Jersey"
                        },
                        new
                        {
                            NationalityId = 112,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            NationalityId = 113,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            NationalityId = 114,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            NationalityId = 115,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            NationalityId = 116,
                            CountryName = "Korea, Democratic Peoples Republic of"
                        },
                        new
                        {
                            NationalityId = 117,
                            CountryName = "Korea, Republic of"
                        },
                        new
                        {
                            NationalityId = 118,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            NationalityId = 119,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            NationalityId = 120,
                            CountryName = "Lao Peoples Democratic Republic"
                        },
                        new
                        {
                            NationalityId = 121,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            NationalityId = 122,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            NationalityId = 123,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            NationalityId = 124,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            NationalityId = 125,
                            CountryName = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            NationalityId = 126,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            NationalityId = 127,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            NationalityId = 128,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            NationalityId = 129,
                            CountryName = "Macao"
                        },
                        new
                        {
                            NationalityId = 130,
                            CountryName = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            NationalityId = 131,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            NationalityId = 132,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            NationalityId = 133,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            NationalityId = 134,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            NationalityId = 135,
                            CountryName = "Mali"
                        },
                        new
                        {
                            NationalityId = 136,
                            CountryName = "Malta"
                        },
                        new
                        {
                            NationalityId = 137,
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            NationalityId = 138,
                            CountryName = "Martinique"
                        },
                        new
                        {
                            NationalityId = 139,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            NationalityId = 140,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            NationalityId = 141,
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            NationalityId = 142,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            NationalityId = 143,
                            CountryName = "Micronesia, Federated States of"
                        },
                        new
                        {
                            NationalityId = 144,
                            CountryName = "Moldova, Republic of"
                        },
                        new
                        {
                            NationalityId = 145,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            NationalityId = 146,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            NationalityId = 147,
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            NationalityId = 148,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            NationalityId = 149,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            NationalityId = 150,
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            NationalityId = 151,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            NationalityId = 152,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            NationalityId = 153,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            NationalityId = 154,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            NationalityId = 155,
                            CountryName = "Netherlands Antilles"
                        },
                        new
                        {
                            NationalityId = 156,
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            NationalityId = 157,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            NationalityId = 158,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            NationalityId = 159,
                            CountryName = "Niger"
                        },
                        new
                        {
                            NationalityId = 160,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            NationalityId = 161,
                            CountryName = "Niue"
                        },
                        new
                        {
                            NationalityId = 162,
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            NationalityId = 163,
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            NationalityId = 164,
                            CountryName = "Norway"
                        },
                        new
                        {
                            NationalityId = 165,
                            CountryName = "Oman"
                        },
                        new
                        {
                            NationalityId = 166,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            NationalityId = 167,
                            CountryName = "Palau"
                        },
                        new
                        {
                            NationalityId = 168,
                            CountryName = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            NationalityId = 169,
                            CountryName = "Panama"
                        },
                        new
                        {
                            NationalityId = 170,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            NationalityId = 171,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            NationalityId = 172,
                            CountryName = "Peru"
                        },
                        new
                        {
                            NationalityId = 173,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            NationalityId = 174,
                            CountryName = "Pitcairn"
                        },
                        new
                        {
                            NationalityId = 175,
                            CountryName = "Poland"
                        },
                        new
                        {
                            NationalityId = 176,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            NationalityId = 177,
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            NationalityId = 178,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            NationalityId = 179,
                            CountryName = "Reunion"
                        },
                        new
                        {
                            NationalityId = 180,
                            CountryName = "Romania"
                        },
                        new
                        {
                            NationalityId = 181,
                            CountryName = "Russian Federation"
                        },
                        new
                        {
                            NationalityId = 182,
                            CountryName = "RWANDA"
                        },
                        new
                        {
                            NationalityId = 183,
                            CountryName = "Saint Helena"
                        },
                        new
                        {
                            NationalityId = 184,
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            NationalityId = 185,
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            NationalityId = 186,
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            NationalityId = 187,
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            NationalityId = 188,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            NationalityId = 189,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            NationalityId = 190,
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            NationalityId = 191,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            NationalityId = 192,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            NationalityId = 193,
                            CountryName = "Serbia and Montenegro"
                        },
                        new
                        {
                            NationalityId = 194,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            NationalityId = 195,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            NationalityId = 196,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            NationalityId = 197,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            NationalityId = 198,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            NationalityId = 199,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            NationalityId = 200,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            NationalityId = 201,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            NationalityId = 202,
                            CountryName = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            NationalityId = 203,
                            CountryName = "Spain"
                        },
                        new
                        {
                            NationalityId = 204,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            NationalityId = 205,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            NationalityId = 206,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            NationalityId = 207,
                            CountryName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            NationalityId = 208,
                            CountryName = "Swaziland"
                        },
                        new
                        {
                            NationalityId = 209,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            NationalityId = 210,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            NationalityId = 211,
                            CountryName = "Syrian Arab Republic"
                        },
                        new
                        {
                            NationalityId = 212,
                            CountryName = "Taiwan, Province of China"
                        },
                        new
                        {
                            NationalityId = 213,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            NationalityId = 214,
                            CountryName = "Tanzania, United Republic of"
                        },
                        new
                        {
                            NationalityId = 215,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            NationalityId = 216,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            NationalityId = 217,
                            CountryName = "Togo"
                        },
                        new
                        {
                            NationalityId = 218,
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            NationalityId = 219,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            NationalityId = 220,
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            NationalityId = 221,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            NationalityId = 222,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            NationalityId = 223,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            NationalityId = 224,
                            CountryName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            NationalityId = 225,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            NationalityId = 226,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            NationalityId = 227,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            NationalityId = 228,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            NationalityId = 229,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            NationalityId = 230,
                            CountryName = "United States"
                        },
                        new
                        {
                            NationalityId = 231,
                            CountryName = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            NationalityId = 232,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            NationalityId = 233,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            NationalityId = 234,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            NationalityId = 235,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            NationalityId = 236,
                            CountryName = "Viet Nam"
                        },
                        new
                        {
                            NationalityId = 237,
                            CountryName = "Virgin Islands, British"
                        },
                        new
                        {
                            NationalityId = 238,
                            CountryName = "Virgin Islands, U.S."
                        },
                        new
                        {
                            NationalityId = 239,
                            CountryName = "Wallis and Futuna"
                        },
                        new
                        {
                            NationalityId = 240,
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            NationalityId = 241,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            NationalityId = 242,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            NationalityId = 243,
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("test_app.Model.Relation", b =>
                {
                    b.Property<int>("RelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RelationshipId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationshipId"));

                    b.Property<string>("RelationshipName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("RelationshipId");

                    b.ToTable("Relations");

                    b.HasData(
                        new
                        {
                            RelationshipId = 1,
                            RelationshipName = "Grand Parents"
                        },
                        new
                        {
                            RelationshipId = 2,
                            RelationshipName = "Parents"
                        },
                        new
                        {
                            RelationshipId = 3,
                            RelationshipName = "Siblings"
                        },
                        new
                        {
                            RelationshipId = 4,
                            RelationshipName = "Spouse"
                        });
                });

            modelBuilder.Entity("test_app.Model.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
